language: go

go:
  - 1.2

before_install:
  - cp .netrc ~
  - chmod 600 .netrc

install:
  - go get -v github.com/heynickc/acronym_validator/validator

script:
  - go test ./validator
  - go test ./data_structures
